[project]
name = "standard-allergen-encoding"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "numpy>=2.4.1",
    "pandas>=3.0.0",
    "wordfreq>=3.1.1",
]
